;
; File generated by co65 v 2.16 - Ubuntu 2.16-2 using model `cc65-module'
;
.fopt		compiler,"co65 v 2.16 - Ubuntu 2.16-2"
.case		on
.debuginfo	off
.export		_joy_driver

;
; CODE SEGMENT
;
.segment	"CODE"
_joy_driver:
	.byte	$6A
	.byte	$6F
	.byte	$79
	.byte	$05
	.byte	$00
	.byte	$00
	.word	_joy_driver+14
	.word	_joy_driver+18
	.word	_joy_driver+19
	.word	_joy_driver+32
	.byte	$A9
	.byte	$00
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$A9
	.byte	$04
	.byte	$AE
	.byte	$D8
	.byte	$FC
	.byte	$E0
	.byte	$A2
	.byte	$F0
	.byte	$01
	.byte	$4A
	.byte	$A2
	.byte	$00
	.byte	$60
	.byte	$29
	.byte	$03
	.byte	$AA
	.byte	$BD
	.byte	$84
	.byte	$02
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$0A
	.byte	$1D
	.byte	$78
	.byte	$02
	.byte	$49
	.byte	$1F
	.byte	$DD
	.word	BSS+0
	.byte	$F0
	.byte	$07
	.byte	$9D
	.word	BSS+0
	.byte	$A2
	.byte	$00
	.byte	$86
	.byte	$4D
	.byte	$A2
	.byte	$00
	.byte	$60

;
; DATA SEGMENT
;
.segment	"DATA"
DATA:

;
; BSS SEGMENT
;
.segment	"BSS"
BSS:
	.res	4

;
; ZEROPAGE SEGMENT
;
.import	__ZP_START__		; Linker generated symbol
ZEROPAGE = __ZP_START__

.end
